on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_runtime:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe 4.3.2
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Check Haxe Version
        run: haxe -version

      - name: Setup Library
        run: haxelib git godot-api-generator "${{ github.workspace }}"

      - name: Test Help
        working-directory: ${{ github.workspace }}
        run: haxelib run godot-api-generator help

      - name: Create Bindings
        working-directory: ${{ github.workspace }}
        run: haxelib run godot-api-generator "${{ github.workspace }}/godot" "test/extension_api.json" 

      - name: Test DevEnv.hxml
        run: haxe DevEnv.hxml