on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_runtime:
    runs-on: windows-latest
    steps:
      - name: Setup Haxe 4.3.0
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Godot
        uses: suisei-cn/actions-download-file@v1.4.0
        id: godotZip  # Remember to give an ID if you need the output
        with:
          url: "https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_win64.exe.zip"
          target: godot/

      - name: Extract Godot
        working-directory: godot
        run: 7z x Godot_v4.1.3-stable_win64.exe.zip -ogodot

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ./generate.bat
          write-mode: overwrite
          contents: |
            ./godot/godot/Godot_v4.1.3-stable_win64.exe --headless --dump-extension-api-with-docs extension_api.json

      - name: Check Haxe Version
        run: haxe -version

      - name: Check Godot Version
        run: ./godot/godot/Godot_v4.1.3-stable_win64.exe --version

      - name: Generate JSON API
        run: ./generate.bat

      - name: Setup Library
        run: haxelib git godot-api-generator .

      - name: Create Bindings
        run: haxelib run godot-api-generator extension_api.json godot

      - name: Test DevEnv.hxml
        run: haxe DevEnv.hxml