on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_runtime:
    runs-on: windows-latest
    steps:
      - name: Setup Haxe 4.3.0
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Haxe Version
        run: haxe -version

      - name: Setup Library
        run: haxelib git godot-api-generator .

      - name: Create Bindings
        run: haxelib run godot-api-generator "data/extension_api.json" ./godot

      - name: Do Bindings Exist?
        run: dir

      - name: Do Bindings Exist? 2
        working-directory: godot
        run: dir

      - name: Test DevEnv.hxml
        run: haxe DevEnv.hxml