on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_runtime:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Haxe 4.3.2
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Check Haxe Version
        run: haxe -version

      - name: EXPOSED
        run: echo ${GITHUB_WORKSPACE}

      - name: Setup Library
        run: haxelib git godot-api-generator "${GITHUB_WORKSPACE}"

      - name: Create Bindings
        working-directory: ${GITHUB_WORKSPACE}
        run: haxelib run godot-api-generator "data/extension_api.json" ./godot

      - name: DIR
        run: dir
      
      - name: DUIR 2
        working-directory: godot
        run: dir

      - name: Test DevEnv.hxml
        run: haxe DevEnv.hxml